### ISSUE TITLE
Anime: Show Twist.moe link in Links

### ISSUE THREAD

**Issue by hazre** [animenotifier/notify.moe#211]
Show the twist.moe link in Links other than just in Home.
Context:
![context](https://i.imgur.com/eV6LGYI.png)

**Comment by hazre** [comment]
or do #212

**Comment by akyoto** [comment]
This will not happen because we're actually working on being more independent in general, that means we're trying to rely less on external sites. The first step, which is to be independent from Kitsu, is almost fully complete, and one of the next steps is to not rely on twist.moe for video contents because it's a variable that we have no control over.

twist.moe will eventually be removed from the site and this has been discussed with @nallown on Discord already. It will take a lot of time but it's one of the future goals.
