### ISSUE TITLE
ability to delete account

### ISSUE THREAD

**Issue by soredake** [animenotifier/notify.moe#235]

**Comment by akyoto** [comment]
This has been discussed multiple times already. The consensus is that this is a really complicated feature that takes a lot of time to implement and that it's not worth for any contributor to waste his time working on it instead of actually improving the site's features. It is better to use that limited time we open source developers have towards making the site better.

**Comment by ghost** [comment]
I would keep the issue open, it still is a valid request after all, you could just add a tag that it won't happen anytime soon or something similar.
